config/routes.rb
Rails.application.routes.draw do
  resources :lawyers
  resources :users

end

app/models/lawyer.rb
class Lawyer < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lawyers_controller.rb
class LawyersController < ApplicationController
  before_action :set_lawyer, only: [:show, :edit, :update, :destroy]

  # GET /lawyers
  # GET /lawyers.json
  def index
    @lawyers = Lawyer.all
  end

  # GET /lawyers/1
  # GET /lawyers/1.json
  def show
  end

  # GET /lawyers/new
  def new
    @lawyer = Lawyer.new
  end

  # GET /lawyers/1/edit
  def edit
  end

  # POST /lawyers
  # POST /lawyers.json
  def create
    @lawyer = Lawyer.new(lawyer_params)

    respond_to do |format|
      if @lawyer.save
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully created.' }
        format.json { render :show, status: :created, location: @lawyer }
      else
        format.html { render :new }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lawyers/1
  # PATCH/PUT /lawyers/1.json
  def update
    respond_to do |format|
      if @lawyer.update(lawyer_params)
        format.html { redirect_to @lawyer, notice: 'Lawyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lawyer }
      else
        format.html { render :edit }
        format.json { render json: @lawyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lawyers/1
  # DELETE /lawyers/1.json
  def destroy
    @lawyer.destroy
    respond_to do |format|
      format.html { redirect_to lawyers_url, notice: 'Lawyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lawyer
      @lawyer = Lawyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lawyer_params
      params.require(:lawyer).permit(:name, :case_type, :case_win, :case_loose, :fee)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show  
    current_user = User.find(params[:id])
    @lawyers = Lawyer.where(:case_type => current_user.case_type)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :case_type, :case_details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lawyers_helper.rb
module LawyersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lawyers/_form.html.erb
<div class="grid-1 gutter-40">
  <div class="span-1">
    <fieldset class="flakes-information-box">
      <%= form_for(@lawyer) do |f| %>
        <% if @lawyer.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@lawyer.errors.count, "error") %> prohibited this lawyer from being saved:</h2>

            <ul>
            <% @lawyer.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :case_type %><br>
          <%= f.number_field :case_type %>
        </div>
        <div class="field">
          <%= f.label :case_win %><br>
          <%= f.number_field :case_win %>
        </div>
        <div class="field">
          <%= f.label :case_loose %><br>
          <%= f.number_field :case_loose %>
        </div>
        <div class="field">
          <%= f.label :fee %><br>
          <%= f.number_field :fee %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
      </fieldset>
  </div>  
</div>  

app/views/lawyers/edit.html.erb
<h1>Editing Lawyer</h1>

<%= render 'form' %>

<%= link_to 'Show', @lawyer %> |
<%= link_to 'Back', lawyers_path %>

app/views/lawyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lawyers</h1>

<table class="flakes-table" style="width:100%" cellpadding="5">
  <thead align="center">
    <tr>
      <th>Name</th>
      <th>Case type</th>
      <th>Case win</th>
      <th>Case loose</th>
      <th>Fee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="center">
    <% @lawyers.each do |lawyer| %>
      <tr>
        <td><%= lawyer.name %></td>
        <td><%= lawyer.case_type %></td>
        <td><%= lawyer.case_win %></td>
        <td><%= lawyer.case_loose %></td>
        <td><%= lawyer.fee %></td>
        <td><%= link_to 'Show', lawyer %></td>
        <td><%= link_to 'Edit', edit_lawyer_path(lawyer) %></td>
        <td><%= link_to 'Destroy', lawyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lawyer', new_lawyer_path %>

app/views/lawyers/new.html.erb
<h1>New Lawyer</h1>

<%= render 'form' %>

<%= link_to 'Back', lawyers_path %>

app/views/lawyers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lawyer.name %>
</p>

<p>
  <strong>Case type:</strong>
  <%= @lawyer.case_type %>
</p>

<p>
  <strong>Case win:</strong>
  <%= @lawyer.case_win %>
</p>

<p>
  <strong>Case loose:</strong>
  <%= @lawyer.case_loose %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @lawyer.fee %>
</p>

<%= link_to 'Edit', edit_lawyer_path(@lawyer) %> |
<%= link_to 'Back', lawyers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LawFirmProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<fieldset>    
<div class="flakes-frame">
<div class="flakes-content">
	<h1>Welcome To Asad's Law Firm</h1>
	We support 4 types of cases. <br>
	<li><legend>1: Murder</legend></li>
	<li><legend>2: Sexual Harrasment</legend></li>
	<li><legend>3: Theft</legend></li>
	<li><legend>4: Divorse</legend></li>

      <div class="view-wrap">
        <%= yield %>
      </div>
    
    </div>
  </div>
</fieldset>
</div>


</body>
</html>

app/views/users/_form.html.erb
<div class="grid-1 gutter-40">
  <div class="span-1">
    <fieldset class="flakes-information-box">
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>
        <div class="field">
          <%= f.label :case_type %><br>
          <%= f.number_field :case_type %>
        </div>
        <div class="field">
          <%= f.label :case_details %><br>
          <%= f.text_area :case_details %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>
      </fieldset>
  </div>  
</div>  

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<fieldset class="flakes-information-box">
<table class="flakes-table" style="width:100%" cellpadding="5">

  <thead>
    <tr>
      <th>Client</th>
      <th>Case Type</th>
      <th></th>
      <th>Case-Details</th>
    </tr>
  </thead>

  <tbody align="center">
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.case_type %></td>
        <td><button><strong><%= link_to 'View List of Lawyers For This Case', user %></strong></button></td>
        <td><%= user.case_details %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button><strong><%= link_to 'Add New User', new_user_path %></strong></button>

</fieldset>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Case type:</strong>
  <%= @user.case_type %>
</p>

<p>
  <strong>Case details:</strong>
  <%= @user.case_details %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

<br>

<h2>Available Lawyers for your case</h2>

<table class="flakes-table" style="width:100%" cellpadding="5">
  <thead align="center">
    <tr>
      <th>Name</th>
      <th>Case type</th>
      <th>Case win</th>
      <th>Case loose</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody align="center">
    <% @lawyers.each do |lawyer| %>
      <tr>
        <td><%= lawyer.name %></td>
        <td><%= lawyer.case_type %></td>
        <td><%= lawyer.case_win %></td>
        <td><%= lawyer.case_loose %></td>
        <td><%= link_to 'Details', lawyer %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>